pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id 'com.android.library' version '8.10.1' apply false
    id 'org.jetbrains.kotlin.android' version '2.1.0' apply false
}

rootProject.name = 'hovr_device_permissions'
include ':hovr_device_permissions'
project(':hovr_device_permissions').projectDir = file('android/hovr_device_permissions')
